[package]
name = "nixos-systool"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "z"
lto = true
overflow-checks = false
panic = "abort"
codegen-units = 1
# Add this once 1.59 lands in `nixpkgs`
#strip = "symbols"

[dependencies]
color-eyre = "0.6"
duct = "0.13"
notify-rust = "4"
owo-colors = "3.2"
structopt = "0.3"
thiserror = "1.0"
