[package]
name = "nixos-systool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "z"
lto = true
overflow-checks = false
panic = "abort"
codegen-units = 1

[dependencies]
duct = "0.13.5"
color-eyre = "0.6.0"
owo-colors = "3.2.0"
structopt = "0.3.26"
thiserror = "1.0.30"
